name: Python CI

on:
  push:
    branches: ["main", "dev"]

jobs:
  build-and-test:
    strategy:
      matrix:
        python-version: ['3.12.6', '3.13']
        os: [ubuntu-latest, macos-latest]
        
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Our Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install UV
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: UV cache
        uses: actions/cache@v5
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install Dependencies
        run: uv sync

      - name: Run Tests in UV
        run:  uv run python -m unittest discover
